### ISSUE TITLE
Параметры транзакции

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn-db#1]
где-то здесь должны задаваться параметры транзакции:

```
    async createTransaction(): Promise<FirebirdTransaction2> {
        if (!this._connect) throw new Error("Need database connection");

        return new FirebirdTransaction2(this._connect);
    }
```

по умолчанию должно быть: read_committed, rec_version, nowait.

**Comment by sywka** [comment]
Какие параметры должны быть доступны по api?

Я думал будет достаточно этих:
```ts
type Options = {
  isolation: "READ_COMMITED" | "READ_UNCOMMITED" | "REPEATABLE_READ" | "SERIALIZABLE",
  accessMode: "READ_WRITE" | "READ_ONLY"
}
```
но тогда не совсем понятно как их связывать с драйвером

**Comment by gsbelarus** [comment]
uncomitted  нет в фб и это противоречит acid. можно не делать.

ср, 4 кра 2018, 14:09 карыстальнік Lomashko Yuri <notifications@github.com>
напісаў:

**Comment by gsbelarus** [comment]
с одной стороны нам надо только 2... с другой можно сделать как в фб все.

ср, 4 кра 2018, 14:53 карыстальнік AK <gs1994@gmail.com> напісаў:

**Comment by sywka** [comment]
А какие 2 нам нужны? 
Как в фб, есть только в фб. Каким образом потом другие базы подключать?
К примеру [postgreSQL](https://www.postgresql.org/docs/9.1/static/sql-start-transaction.html), там набор параметров как по стандарту, без всяких дополнительных опций как в фб.

**Comment by gsbelarus** [comment]
мы используем только read comitted или snapshot. у нас всегда rec version и
всегда nowait.

ср, 4 кра 2018, 15:11 карыстальнік Lomashko Yuri <notifications@github.com>
напісаў:
