### ISSUE TITLE
Имена параметров в запросах. Метод ParamByName или объект с параметрами.

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn-db#2]
Именованные параметры. Код рабочий и проверенный годами здесь:

`procedure TIBSQL.PreprocessSQL;`

надо портировать с делфи.

**Comment by sywka** [comment]
Done in [commit](https://github.com/gsbelarus/gdmn-db/commit/b10aa96a39567480073e5d9320fde229910ef263)
