### ISSUE TITLE
Параметры транзакции

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn-db#22]
А где указываются параметры транзакции? Их вообще-то много. В большинстве случаев мы применяем:

![image](https://user-images.githubusercontent.com/5175764/44924844-3f434a00-ad55-11e8-8f3b-76fd79fc596d.png)

Но могут понадобиться и другие. Например, snapshot транзакции для отчетов.

**Comment by sywka** [comment]
Параметры транзакции как таковые из апи не задаются. По апи доступны 4 стандартных типа транзакций (чтобы можно было в будущем легко подключить другие бд) и уровни доступа.

## Типы транзакций и их реализация для драйвера Firebird:

#### READ_COMMITED
Используются флаги Firebird:
* READ_COMMITTED
* RECORD_VERSION
* NO_WAIT

#### READ_UNCOMMITED
По идее не поддерживается, но пока реализован как READ_COMMITED с флагом NO_RECORD_VERSION

#### REPEATABLE_READ
Используются флаги Firebird:
* SNAPSHOT (CONCURRENCY)
* NO_WAIT

#### SERIALIZABLE
Используются флаги Firebird:
* CONSISTENCY
* NO_WAIT

## Уровни доступа
* READ_ONLY
* READ_WRITE
