### ISSUE TITLE
resultSet.getString и текстовые блобы

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn-db#4]
Если поле базы данных имеет тип BLOB SUB_TYPE 1, т.е. это текстовый блоб, то навреное resultSet.getString должен возвращать строку. Т.е. внутренне выкачивать весь блоб и помещать его в строку.

**Comment by sywka** [comment]
Доступа к схеме базы данных на этом уровне нет, такое возможно только на уровне приложения. В данном случае можно сделать так:
Все методы get для типов сделать асинхронными (пометить как async)
Для метода getString, в случае если поле имеет тип blob выкачивать его как string, независимо от sub type. Во всех других просто возвращать о результат как строку.
