### ISSUE TITLE
Возможность извлечения значения колонки по алиасу поля в запросе

### ISSUE THREAD

**Issue by sywka** [gsbelarus/gdmn-db#6]
[see](https://github.com/asfernandes/node-firebird-driver-native/issues/9)

**Comment by gsbelarus** [comment]
Если делать, то на уровне драйвера через форки и потом пулить в его репозитории.

Я бы существующий метод оставлял как есть и делал к нему второй, который будет возвращать объект.

Заодно вынес бы на уровень стэйтмента что-то вроде Fields как в Делфи. В гедымине нам нужна была информация не только об алиасе, но и о таблице.поле. И прочая информация о типе данных.

**Comment by sywka** [comment]
Есть вариант вообще отказаться от node-firebird-driver и node-firebird-driver-native, т.к. по сути для нас это лишняя прослойка кода. Использовать чисто node-firebird-native-api в качестве моста к fbclient.dll, адаптировав его под наше абстрактное апи. Тогда и форков никаких не надо, и производительность увеличится.

**Comment by gsbelarus** [comment]
можно и так

**Comment by gsbelarus** [comment]
даже лучше будет.

**Comment by sywka** [comment]
[Сделано](https://github.com/gsbelarus/gdmn-db/commit/b5cc161f0f88f856d1c91f4532a0dd8c8253517c), осталось как следует протестировать и возможно поправить баги.
