### ISSUE TITLE
executeResultSet

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn-db#8]
Этот код будет выглядеть менее диковинно, если статический метод executeResultSet перенести в объект соединения/базы данных, а не транзакции.

`await ATransaction.executeResultSet(transaction,`

**Comment by sywka** [comment]
Статические методы `ClassName.executeXXX` находятся в классах, в которых есть методы возвращающие `XXX`, если `XXX `требуют закрытия после завершения работы с ними. Эти статические методы существуют для упрощение работы с закрываемыми объектами.

т.е. когда в классе `Atransaction` есть метод `executeQuery` возвращающий объект `AResultSet` требующий вызова метода `resultSet.close()` в конце, то в этом классе присутствует статический метод `ATransaction.executeResultSet` в колбэке которого можно выполнить какие либо действия с `resultSet` и после завершения работы с ним он автоматически закроется.

Возможно название этих статических методов немного вводит в заблуждение, тогда их можно переназвать. 
Так же можно добавить такие методы в классы более высокого уровня. т.е. к примеру, если сейчас для выполнения запроса возвращающего `AResultSet` нужно выполнить код
```ts
await AConnection.executeTransaction(connection,
  (transaction) => ATransaction.executeResultSet(transaction, "some select", someParams,
    async (resultSet) => {
      // do some work
    })
  );
```
добавив дополнительный статический метод `executeResultSet` в класс `ATransaction` можно в некоторых случаях сократить объем кода
```ts
await AConnection.executeResultSet(connection, "some select", someParams,
    async (resultSet) => {
      // do some work
    })
  );
```
в этом случае метод `executeResultSet` создаст и откроет транзакцию, выполнит запрос, а по завершении работы закроет `resultSet` и транзакцию

**Comment by sywka** [comment]
[Сделано](https://github.com/gsbelarus/gdmn-db/commit/3432215f34e5ae45e27369273ec272d9a53487c9)
